/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bb_leveldb_DB_Snapshot */

#ifndef _Included_com_bb_leveldb_DB_Snapshot
#define _Included_com_bb_leveldb_DB_Snapshot
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
